language: scala

dist: trusty

jdk:
  - oraclejdk8

scala:
  - 2.12.2

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database gem' -U postgres

env:
  - TRAVIS_NODE_VERSION="5.12.0"
  - TRAVIS_NODE_VERSION="6.10.0"
  - TRAVIS_NODE_VERSION="7.6.0"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

script:
  - sbt headerCheck test:headerCheck scalastyle sql/flywayMigrate compile test

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 2 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
